def ajuda():
    print("-------------------------------------")
    print("               |HELP|                ")
    print("-------------------------------------")
    print("     |INSTRUÇÕES DE COMO JOGAR|      ")
    print("-----------------------------------------------")
    print("Ao iniciar o jogo você  já começa com 10 moedas")
    print("                                               ")
    print("em seguida você  podera escolhe se quer apostar")
    print("em TRINCA ou PAR, se  você  escolher  PAR, só")
    print("ganhara  moedas se  aparecer um par dos  mesmos") 
    print("elementos na tela,Se escolher TRINCA só ganhara")
    print("moedas se aparecer um trio dos mesmos elementos")
    print("                                               ")
    print("depois  você vai dizer o quanto quer apostar, o")
    print("valor não  poderar ser  menor que zero ou maior")
    print("que a quantidade de moedas que você possui.    ")
    print("                                               ")
    print("Se você perder, sera descontado das suas moedas")
    print("a quantia que você apostou, se for bem sucedido")
    print("no  sorteio podera ganhar  10 moedas, 15 moedas")
    print("ou 50 moedas. vai depender do resultado.       ")
    print("Se no  sorteio aparecer o [$] cifrão da sorte  ")
    print("você ganhara 10 moedas de bonus automatimente. ")
    print("                                               ")
    print("os pontos são o valor do premio em moedas vezes")
    print("o valor de moedas apostado.                    ")
    print("-----------------------------------------------")
